import type { Designer } from "./types";

export const designers: Designer[] = [
  {
    id: "vesper",
    slug: "vesper",
    name: "VESPER",
    tagline: "Architecture for the body",
    shortBio: "Berlin-based conceptual fashion studio exploring the intersection of structure and silence.",
    story: [
      "VESPER was born in a converted factory in Prenzlauer Berg, where industrial geometry meets the quiet severity of Bauhaus principle.",
      "Founded by Mira Hoffmann in 2019, the studio treats garments as architectural propositions — each piece a study in tension, weight, and negative space.",
      "Every collection is produced in edition runs of no more than forty pieces. No exceptions.",
      "We don't make clothes. We make decisions.",
    ],
    location: "Berlin, Germany",
    founded: "2019",
    featuredGradient: "#0d0d0d",
    logoMark: "VESPER",
    theme: {
      bg: "#080808",
      fg: "#f0f0f0",
      accent: "#0d0d0d",
      accentText: "#ffffff",
      accentSecondary: "#606060",
      fontDisplay: "'Playfair Display', Georgia, serif",
      fontBody: "'Space Mono', monospace",
      fontMono: "'Space Mono', monospace",
      mood: "brutalist",
      motionSpeed: "slow",
      cssVars: {
        "--d-bg": "#080808",
        "--d-bg-2": "#111111",
        "--d-fg": "#f0f0f0",
        "--d-fg-dim": "#808080",
        "--d-accent": "#ffffff",
        "--d-accent-2": "#404040",
        "--d-border": "rgba(255,255,255,0.08)",
        "--d-glow": "rgba(255,255,255,0.15)",
      },
    },
    products: [
      {
        id: "vesper-01",
        name: "Void Jacket",
        price: 2800,
        category: "Outerwear",
        description: "Deconstructed double-breasted jacket in heavyweight boiled wool. Exposed seams, weighted hem, architectural silhouette.",
        material: "100% Italian boiled wool, brass hardware",
        colorway: "#111111",
        designerId: "vesper",
        featured: true,
        tags: ["editorial", "statement", "winter"],
      },
      {
        id: "vesper-02",
        name: "Meridian Trousers",
        price: 980,
        category: "Bottoms",
        description: "High-waisted wide-leg trousers with vertical pressed seam lines creating optical parallels down the leg.",
        material: "Wool gabardine",
        colorway: "#1e1e1e",
        designerId: "vesper",
        featured: true,
        tags: ["tailoring", "essential"],
      },
      {
        id: "vesper-03",
        name: "Axis Coat",
        price: 4200,
        category: "Outerwear",
        description: "Floor-length asymmetric coat with singular off-center closure. The defining piece of AW24.",
        material: "Cashmere blend, silk lining",
        colorway: "#0a0a0a",
        designerId: "vesper",
        featured: false,
        tags: ["couture", "winter", "statement"],
      },
      {
        id: "vesper-04",
        name: "Column Dress",
        price: 1650,
        category: "Dresses",
        description: "Minimal column dress with internal boning that holds form independently of the body.",
        material: "Technical crepe",
        colorway: "#151515",
        designerId: "vesper",
        featured: false,
      },
    ],
    lookbook: [
      { id: "v-lb-1", alt: "Void Jacket — studio shot", gradient: "#0a0a0a", span: "tall" },
      { id: "v-lb-2", alt: "Meridian Trousers — movement study", gradient: "#141414", span: "normal" },
      { id: "v-lb-3", alt: "AW24 campaign — exterior", gradient: "#0d0d0d", span: "wide" },
      { id: "v-lb-4", alt: "Column dress — detail", gradient: "#111111", span: "normal" },
      { id: "v-lb-5", alt: "Axis Coat — full length", gradient: "#080808", span: "tall" },
    ],
  },

  {
    id: "nova-aura",
    slug: "nova-aura",
    name: "NOVA AURA",
    tagline: "Jewellery from parallel futures",
    shortBio: "Tokyo-Seoul conceptual jewellery studio. Objects that exist at the edge of material and light.",
    story: [
      "NOVA AURA was conceived in 2021 in a neon-lit studio overlooking Shibuya, by jeweller Yuki Tanaka and material scientist Seo Jiwon.",
      "Each piece is a proposition: what if light itself could be worn? The studio explores electroformed metals, reactive alloys, and photoluminescent enamels.",
      "Collections are named after theoretical physics phenomena. The current body of work is titled 'Event Horizon Series IV'.",
      "We make things that don't belong to any decade. They are artefacts from a timeline adjacent to this one.",
    ],
    location: "Tokyo & Seoul",
    founded: "2021",
    featuredGradient: "#00ECFF",
    logoMark: "NOVA AURA",
    theme: {
      bg: "#04040f",
      fg: "#e0e8ff",
      accent: "#00ECFF",
      accentText: "#000000",
      accentSecondary: "#ff00aa",
      fontDisplay: "'Space Grotesk', 'DM Sans', sans-serif",
      fontBody: "'Space Grotesk', sans-serif",
      fontMono: "'Space Mono', monospace",
      mood: "futuristic",
      motionSpeed: "fast",
      cssVars: {
        "--d-bg": "#04040f",
        "--d-bg-2": "#08081f",
        "--d-fg": "#e0e8ff",
        "--d-fg-dim": "#6080a0",
        "--d-accent": "#00f0ff",
        "--d-accent-2": "#ff00aa",
        "--d-border": "rgba(0,240,255,0.12)",
        "--d-glow": "rgba(0,240,255,0.25)",
      },
    },
    products: [
      {
        id: "nova-01",
        name: "Quasar Ring",
        price: 1200,
        category: "Rings",
        description: "Electroformed sterling silver ring with photoluminescent cyan enamel core. Glows under UV.",
        material: "Electroformed sterling silver, photoluminescent enamel",
        colorway: "#00ECFF",
        designerId: "nova-aura",
        featured: true,
        tags: ["statement", "luminescent", "silver"],
      },
      {
        id: "nova-02",
        name: "Pulsar Cuff",
        price: 3400,
        category: "Bracelets",
        description: "Kinetic cuff in titanium with embedded magnetic spheres that orbit a central channel.",
        material: "Grade 5 titanium, neodymium spheres",
        colorway: "#00c8dd",
        designerId: "nova-aura",
        featured: true,
        tags: ["kinetic", "titanium", "statement"],
      },
      {
        id: "nova-03",
        name: "Event Horizon Pendant",
        price: 2100,
        category: "Necklaces",
        description: "Dual-layered pendant — outer ring in oxidised silver, inner sphere of reactive bismuth alloy that shifts colour with temperature.",
        material: "Oxidised sterling silver, bismuth alloy",
        colorway: "#00a8bb",
        designerId: "nova-aura",
        featured: false,
        tags: ["reactive", "silver", "necklace"],
      },
      {
        id: "nova-04",
        name: "Singularity Earrings",
        price: 890,
        category: "Earrings",
        description: "Asymmetric earrings: one is a perfect sphere, one is a crushed form. Each pair is unique.",
        material: "Brushed 18k white gold",
        colorway: "#00ECFF",
        designerId: "nova-aura",
        featured: false,
      },
    ],
    lookbook: [
      { id: "n-lb-1", alt: "Quasar Ring — UV study", gradient: "#00ECFF", span: "tall" },
      { id: "n-lb-2", alt: "Pulsar Cuff — detail", gradient: "#00c8dd", span: "normal" },
      { id: "n-lb-3", alt: "Event Horizon campaign", gradient: "#00ECFF", span: "wide" },
      { id: "n-lb-4", alt: "Singularity Earrings", gradient: "#00a8bb", span: "normal" },
      { id: "n-lb-5", alt: "Studio — material exploration", gradient: "#00ECFF", span: "tall" },
    ],
  },

  {
    id: "terra",
    slug: "terra",
    name: "TERRA",
    tagline: "Slow fashion from living materials",
    shortBio: "Oaxacan textiles studio rooted in ancestral dyeing techniques and regenerative craft.",
    story: [
      "TERRA emerged from a collaboration between textile artist Lucía Reyes and her grandmother, master weaver Doña Carmen, in the mountains of Oaxaca.",
      "Every garment begins with the earth — natural indigo fermentation vats, cochineal dye baths, walnut hull mordants harvested seasonally.",
      "The studio employs twelve artisan weavers from the local community. Production is measured in weeks, not days.",
      "TERRA makes things that will outlast you. That is the only metric that matters.",
    ],
    location: "Oaxaca, Mexico",
    founded: "2020",
    featuredGradient: "#E8552A",
    logoMark: "TERRA",
    theme: {
      bg: "#f2ece4",
      fg: "#2c1f17",
      accent: "#E8552A",
      accentText: "#ffffff",
      accentSecondary: "#8b5e42",
      fontDisplay: "'Lora', 'DM Serif Display', Georgia, serif",
      fontBody: "'Lora', Georgia, serif",
      fontMono: "'Space Mono', monospace",
      mood: "earthy",
      motionSpeed: "slow",
      cssVars: {
        "--d-bg": "#f2ece4",
        "--d-bg-2": "#e8ddd0",
        "--d-fg": "#2c1f17",
        "--d-fg-dim": "#7a6050",
        "--d-accent": "#E8552A",
        "--d-accent-2": "#8b5e42",
        "--d-border": "rgba(44,31,23,0.12)",
        "--d-glow": "rgba(232,85,42,0.2)",
      },
    },
    products: [
      {
        id: "terra-01",
        name: "Indigo Field Dress",
        price: 1850,
        category: "Dresses",
        description: "Natural indigo resist-dyed dress woven on a backstrap loom. Each piece unique in its dye pattern.",
        material: "Hand-spun cotton, natural indigo",
        colorway: "#E8552A",
        designerId: "terra",
        featured: true,
        tags: ["handwoven", "natural dye", "one-of-a-kind"],
      },
      {
        id: "terra-02",
        name: "Cochineal Shawl",
        price: 680,
        category: "Accessories",
        description: "Large-format shawl dyed with cochineal, yielding a spectrum from deep crimson to soft coral depending on mordant.",
        material: "Merino wool, cochineal dye",
        colorway: "#c8441d",
        designerId: "terra",
        featured: true,
        tags: ["natural dye", "wrap", "artisan"],
      },
      {
        id: "terra-03",
        name: "Walnut Linen Coat",
        price: 2400,
        category: "Outerwear",
        description: "Relaxed linen coat dyed with walnut shells and oak galls. Deepens in colour with age and sunlight.",
        material: "Belgian linen, natural walnut & oak gall dye",
        colorway: "#d04820",
        designerId: "terra",
        featured: false,
        tags: ["linen", "natural dye", "investment piece"],
      },
      {
        id: "terra-04",
        name: "Clay Vessel Earrings",
        price: 290,
        category: "Jewellery",
        description: "Miniature ceramic vessels handformed and pit-fired by local ceramicist Luis Mendoza. Sterling silver wire.",
        material: "Pit-fired clay, sterling silver",
        colorway: "#E8552A",
        designerId: "terra",
        featured: false,
      },
    ],
    lookbook: [
      { id: "t-lb-1", alt: "Indigo Field — morning light", gradient: "#E8552A", span: "tall" },
      { id: "t-lb-2", alt: "Cochineal dye process", gradient: "#c8441d", span: "normal" },
      { id: "t-lb-3", alt: "Walnut Coat — field", gradient: "#d04820", span: "wide" },
      { id: "t-lb-4", alt: "Weaving studio — Doña Carmen", gradient: "#E8552A", span: "normal" },
      { id: "t-lb-5", alt: "Clay Vessels — collection", gradient: "#b83c18", span: "tall" },
    ],
  },

  {
    id: "lumi",
    slug: "lumi",
    name: "LUMI",
    tagline: "Afrofuturist maximalism, made in Lagos",
    shortBio: "Lagos-based atelier fusing Yoruba textile traditions with radical contemporary silhouettes.",
    story: [
      "LUMI was founded by Adaeze Okonkwo in 2022 from a small atelier in Victoria Island, Lagos, where she had been making custom pieces for musicians and artists.",
      "The brand draws on Aso-oke weaving, Adire resist-dyeing, and bold Ankara prints — but refuses to be nostalgic. These are forward-looking garments.",
      "Each collection is named after an element. The current season is 'ZINC'.",
      "Loudness is not the absence of intention. It is the fullest expression of it.",
    ],
    location: "Lagos, Nigeria",
    founded: "2022",
    featuredGradient: "#C8FF00",
    logoMark: "LUMI",
    theme: {
      bg: "#0a0a00",
      fg: "#f5f5e0",
      accent: "#C8FF00",
      accentText: "#000000",
      accentSecondary: "#a0cc00",
      fontDisplay: "'Cormorant Garamond', Georgia, serif",
      fontBody: "'Inter', system-ui, sans-serif",
      fontMono: "'Space Mono', monospace",
      mood: "vibrant",
      motionSpeed: "fast",
      cssVars: {
        "--d-bg": "#0a0a00",
        "--d-bg-2": "#151500",
        "--d-fg": "#f5f5e0",
        "--d-fg-dim": "#a0a060",
        "--d-accent": "#C8FF00",
        "--d-accent-2": "#a0cc00",
        "--d-border": "rgba(200,255,0,0.15)",
        "--d-glow": "rgba(200,255,0,0.3)",
      },
    },
    products: [
      {
        id: "lumi-01",
        name: "Zinc Volume Jacket",
        price: 1980,
        category: "Outerwear",
        description: "Exaggerated-shoulder jacket in hand-woven Aso-oke with acid-dyed silk lining. Statement sleeve volume.",
        material: "Hand-woven Aso-oke, acid-dyed silk",
        colorway: "#C8FF00",
        designerId: "lumi",
        featured: true,
        tags: ["statement", "handwoven", "maximalist"],
      },
      {
        id: "lumi-02",
        name: "Adire Wide Trousers",
        price: 740,
        category: "Bottoms",
        description: "Fluid wide-leg trousers in Adire-dyed cotton. Each pair unique in its indigo resist pattern.",
        material: "100% cotton, Adire indigo dye",
        colorway: "#aad900",
        designerId: "lumi",
        featured: true,
        tags: ["natural dye", "wide-leg", "artisan"],
      },
      {
        id: "lumi-03",
        name: "Ceremony Gown",
        price: 3600,
        category: "Dresses",
        description: "Floor-sweeping gown combining Aso-oke panels with contemporary draping. Commission-only afterpiece.",
        material: "Aso-oke, French chiffon",
        colorway: "#b8ee00",
        designerId: "lumi",
        featured: false,
        tags: ["couture", "ceremony", "statement"],
      },
      {
        id: "lumi-04",
        name: "Lagos Cowrie Necklace",
        price: 480,
        category: "Jewellery",
        description: "Oversized cowrie shell collar handstrung with brass beads. Contemporary heirloom.",
        material: "Cowrie shells, brass, cotton cord",
        colorway: "#C8FF00",
        designerId: "lumi",
        featured: false,
        tags: ["jewellery", "statement", "handmade"],
      },
    ],
    lookbook: [
      { id: "l-lb-1", alt: "Zinc Volume Jacket — Lagos rooftop", gradient: "#C8FF00", span: "tall" },
      { id: "l-lb-2", alt: "Adire dyeing process", gradient: "#aad900", span: "normal" },
      { id: "l-lb-3", alt: "ZINC campaign", gradient: "#C8FF00", span: "wide" },
      { id: "l-lb-4", alt: "Ceremony Gown — studio", gradient: "#b8ee00", span: "normal" },
      { id: "l-lb-5", alt: "Cowrie Necklace — detail", gradient: "#C8FF00", span: "tall" },
    ],
  },

  {
    id: "soleil",
    slug: "soleil",
    name: "SOLEIL",
    tagline: "Demi-couture for the unapologetic",
    shortBio: "Paris atelier making voluminous, pink-blooded demi-couture for women who refuse to be quiet.",
    story: [
      "SOLEIL was founded in 2021 by Camille Voss, a former pattern-cutter at a major Parisian house who decided she was done making clothes for other people's vision.",
      "The studio occupies a salmon-pink atelier in the 10th arrondissement and produces just two collections per year, each consisting of fewer than thirty garments.",
      "Every piece is hand-finished. Zips are never exposed. Hems are always double-turned.",
      "Joy is not frivolous. Joy is the whole point.",
    ],
    location: "Paris, France",
    founded: "2021",
    featuredGradient: "#FF1A5E",
    logoMark: "SOLEIL",
    theme: {
      bg: "#1a000a",
      fg: "#ffe8f0",
      accent: "#FF1A5E",
      accentText: "#ffffff",
      accentSecondary: "#cc0040",
      fontDisplay: "'Cormorant Garamond', Georgia, serif",
      fontBody: "'Inter', system-ui, sans-serif",
      fontMono: "'Space Mono', monospace",
      mood: "romantic",
      motionSpeed: "medium",
      cssVars: {
        "--d-bg": "#1a000a",
        "--d-bg-2": "#250010",
        "--d-fg": "#ffe8f0",
        "--d-fg-dim": "#cc8099",
        "--d-accent": "#FF1A5E",
        "--d-accent-2": "#cc0040",
        "--d-border": "rgba(255,26,94,0.18)",
        "--d-glow": "rgba(255,26,94,0.35)",
      },
    },
    products: [
      {
        id: "soleil-01",
        name: "Pétale Gown",
        price: 4800,
        category: "Dresses",
        description: "Strapless silk gazar gown with hand-sewn petal layering across the bodice. Takes 80 hours to produce.",
        material: "French silk gazar, boned bodice, silk lining",
        colorway: "#FF1A5E",
        designerId: "soleil",
        featured: true,
        tags: ["couture", "evening", "silk"],
      },
      {
        id: "soleil-02",
        name: "Éclair Blouse",
        price: 860,
        category: "Tops",
        description: "Voluminous bishop-sleeve blouse in duchess satin. Hidden snap fastening at cuffs.",
        material: "Italian duchess satin",
        colorway: "#e0144a",
        designerId: "soleil",
        featured: true,
        tags: ["statement", "silk", "evening"],
      },
      {
        id: "soleil-03",
        name: "Midinette Skirt",
        price: 1100,
        category: "Bottoms",
        description: "Midi circle skirt in double-faced wool with internal petticoat. Unlined silhouette at hem.",
        material: "Double-faced wool, cotton petticoat",
        colorway: "#FF1A5E",
        designerId: "soleil",
        featured: false,
        tags: ["wool", "midi", "statement"],
      },
      {
        id: "soleil-04",
        name: "Velours Clutch",
        price: 480,
        category: "Accessories",
        description: "Hand-embroidered velvet clutch with brass frame closure. One-of-a-kind embroidery per piece.",
        material: "French velvet, brass frame, silk lining",
        colorway: "#cc0040",
        designerId: "soleil",
        featured: false,
        tags: ["accessories", "velvet", "embroidered"],
      },
    ],
    lookbook: [
      { id: "s-lb-1", alt: "Pétale Gown — studio", gradient: "#FF1A5E", span: "tall" },
      { id: "s-lb-2", alt: "Éclair Blouse — Marais", gradient: "#e0144a", span: "normal" },
      { id: "s-lb-3", alt: "SS25 campaign", gradient: "#FF1A5E", span: "wide" },
      { id: "s-lb-4", alt: "Midinette Skirt — detail", gradient: "#cc0040", span: "normal" },
      { id: "s-lb-5", alt: "Velours Clutch — studio", gradient: "#FF1A5E", span: "tall" },
    ],
  },

  {
    id: "ondo",
    slug: "ondo",
    name: "ONDO",
    tagline: "Deconstructed tailoring, reconsidered",
    shortBio: "Seoul-based conceptual studio making rigorous, architectural garments from deconstructed tailoring codes.",
    story: [
      "ONDO was founded in 2023 by Park Jisoo, who spent six years studying at Esmod Paris before returning to Seoul to unlearn everything.",
      "The name comes from the Korean word for temperature. Every collection is organised around a thermal concept: conduction, insulation, radiance.",
      "Garments are produced in a workshop in Seongsu-dong in runs of under thirty. Each is finished by a single maker from first cut to final press.",
      "We are interested in what happens when structure is made visible. Not deconstructed — revealed.",
    ],
    location: "Seoul, South Korea",
    founded: "2023",
    featuredGradient: "#1633FF",
    logoMark: "ONDO",
    theme: {
      bg: "#000814",
      fg: "#e0e8ff",
      accent: "#1633FF",
      accentText: "#ffffff",
      accentSecondary: "#0020cc",
      fontDisplay: "'Cormorant Garamond', Georgia, serif",
      fontBody: "'Inter', system-ui, sans-serif",
      fontMono: "'Space Mono', monospace",
      mood: "minimal",
      motionSpeed: "medium",
      cssVars: {
        "--d-bg": "#000814",
        "--d-bg-2": "#001020",
        "--d-fg": "#e0e8ff",
        "--d-fg-dim": "#6080c0",
        "--d-accent": "#1633FF",
        "--d-accent-2": "#0020cc",
        "--d-border": "rgba(22,51,255,0.2)",
        "--d-glow": "rgba(22,51,255,0.35)",
      },
    },
    products: [
      {
        id: "ondo-01",
        name: "Conduction Blazer",
        price: 2200,
        category: "Tailoring",
        description: "Single-button blazer with exposed canvas interlining and floating chest piece. Baste-stitching left visible as design element.",
        material: "Italian wool, horsehair canvas, silk sleeve lining",
        colorway: "#1633FF",
        designerId: "ondo",
        featured: true,
        tags: ["tailoring", "conceptual", "statement"],
      },
      {
        id: "ondo-02",
        name: "Radiance Trousers",
        price: 890,
        category: "Bottoms",
        description: "Wide-leg trousers with unpressed pleats and visible seam tape at waistband. Rigorous and effortless.",
        material: "Wool-mohair blend",
        colorway: "#0020cc",
        designerId: "ondo",
        featured: true,
        tags: ["tailoring", "wide-leg", "minimal"],
      },
      {
        id: "ondo-03",
        name: "Insulation Overcoat",
        price: 3100,
        category: "Outerwear",
        description: "Oversized wool overcoat with structured shoulder pad exposed through sleeve opening. Quilted lining detaches.",
        material: "Double-weave wool, quilted silk lining",
        colorway: "#1633FF",
        designerId: "ondo",
        featured: false,
        tags: ["outerwear", "conceptual", "winter"],
      },
      {
        id: "ondo-04",
        name: "Seongsu Shirt",
        price: 640,
        category: "Tops",
        description: "Boxy unlined shirt with visible interlining at collar and placket. Worn open or buttoned — both are correct.",
        material: "Cotton poplin, cotton interlining",
        colorway: "#0028ee",
        designerId: "ondo",
        featured: false,
        tags: ["shirt", "conceptual", "minimal"],
      },
    ],
    lookbook: [
      { id: "o-lb-1", alt: "Conduction Blazer — Seongsu-dong", gradient: "#1633FF", span: "tall" },
      { id: "o-lb-2", alt: "Radiance Trousers — studio", gradient: "#0020cc", span: "normal" },
      { id: "o-lb-3", alt: "THERMAL campaign", gradient: "#1633FF", span: "wide" },
      { id: "o-lb-4", alt: "Insulation Overcoat — detail", gradient: "#0028ee", span: "normal" },
      { id: "o-lb-5", alt: "Workshop — Seongsu-dong", gradient: "#1633FF", span: "tall" },
    ],
  },
];

export function getDesigner(slug: string): Designer | undefined {
  return designers.find((d) => d.slug === slug);
}

export function getAllProducts() {
  return designers.flatMap((d) => d.products);
}

export function getFeaturedProducts() {
  return designers.flatMap((d) => d.products.filter((p) => p.featured));
}
